# -*- coding: utf-8 -*-
"""Untitled54.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oAkmhi5Rdu1LJW9lLz4iodf4A5-D_aD7
"""

import streamlit as st
import pandas as pd
import os

st.title("Insurance Form Automation")

st.header("Personal Details")

name = st.text_input("Name")
gender = st.selectbox("Gender", ["Male", "Female", "Other"])
age = st.number_input("Age (Years)", min_value=0, max_value=120, step=1)
age_months = st.number_input("Age (Months)", min_value=0, max_value=11, step=1)
contact_number = st.text_input("Contact Number")
insurance_id = st.text_input("Insurance ID Number")
policy_number = st.text_input("Policy Number")
current_address = st.text_area("Current Address")
occupation = st.text_input("Occupation")
dob = st.date_input("Date of Birth")

st.header("Hospital / Insurer Details")

hospital_name = st.text_input("Name of Hospital")
hospital_address = st.text_area("Hospital Address")
rohini_id = st.text_input("Rohini ID")
email_id = st.text_input("Hospital Email ID")

if st.button("Submit Form"):
    # Prepare data
    data = {
        "Name": name,
        "Gender": gender,
        "Age (Years)": age,
        "Age (Months)": age_months,
        "Contact Number": contact_number,
        "Insurance ID": insurance_id,
        "Policy Number": policy_number,
        "Current Address": current_address,
        "Occupation": occupation,
        "Date of Birth": str(dob),
        "Hospital Name": hospital_name,
        "Hospital Address": hospital_address,
        "Rohini ID": rohini_id,
        "Hospital Email": email_id
    }

    df = pd.DataFrame([data])

    # Save to CSV
    file_path = "insurance_data.csv"
    if os.path.exists(file_path):
        df.to_csv(file_path, mode='a', header=False, index=False)
    else:
        df.to_csv(file_path, index=False)

    st.success("✅ Data stored successfully!")

    st.write("### Saved Data Preview:")
    st.write(df)